[package]
name = "clahe-rs"
version = "0.1.0"
authors = ["Micah Chambers <micahc.vt@gmail.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0"
num-traits = "0"
